services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: p3r4o
      MYSQL_DATABASE: virtualshop_main
    ports:
      - "3306:3306"
    networks:
      - ms-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  eureka-server:
    build: ./Eureka-Server
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - ms-network
    depends_on:
      mysql:
        condition: service_healthy

  api-gateway:
    build: ./gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka-server
    networks:
      - ms-network

  client-service:
    build: ./Client
    container_name: client-service
    ports:
      - "8085:8085"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/clients
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka-server
      - mysql
    networks:
      - ms-network

  product-service:
    build: ./Products
    container_name: product-service
    ports:
      - "8084:8084"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/products
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka-server
      - mysql
    networks:
      - ms-network

  user-service:
    build: ./Users
    container_name: user-service
    ports:
      - "8086:8086"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/users
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka-server
      - mysql
    networks:
      - ms-network

  sale-service:
    build: ./Sales
    container_name: sale-service
    ports:
      - "8082:8082"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/sales
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka-server
      - mysql
    networks:
      - ms-network

  saledetail-service:
    build: ./Sales-Details
    container_name: saledetail-service
    ports:
      - "8081:8081"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/salesdetails
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka-server
      - mysql
    networks:
      - ms-network

  provider-service:
    build: ./Providers
    container_name: provider-service
    ports:
      - "8083:8083"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/providers
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka-server
      - mysql
    networks:
      - ms-network

networks:
  ms-network:
    driver: bridge